backend:
  name: git-gateway
  branch: maaster
media_folder: static/img
public_folder: /img
collections:
  - name: 'dashboard'
    label: 'Dashboard item'
    folder: 'content/dashboard'
    create: true
    
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }